### ISSUE TITLE
Merge upstream changes

### ISSUE THREAD

**Issue by kichikuou** [kichikuou/system3-sdl2#2]
TOTO's System3 for Win32 has been [updated on 2020/3/21](http://takeda-toshiya.my.coocan.jp/alice/), for the first time in 4 years. It includes some general improvements and bug fixes, and adds support for more games.

As system3-sdl2 has diverged heavily from TOTO's, merging it would require significant amount of manual work.

**Comment by kichikuou** [comment]
@RottenBlock Heads up, as this may conflict with your work.

**Comment by RottenBlock** [comment]
Wow, who'd have predicted? I'll have to give it a close look! I'm glad to see he's taking a cue from you as well, according to the patch notes. Should be interesting to see!

**Comment by RottenBlock** [comment]
I've given the code a careful look using WinMerge, and I can break down the changes a little:

- Style changes, harmless.
- Changes that aren't relevant to System3-SDL2, like Windows-specific file loading changes.
- Simple changes that can be copy and pasted into System3-SDL2 as-is.
- Only a small handful of changes that might require complex fixes.

Because I like to take notes as I work, I've come up with a summary of all the changes. I mostly wrote them for myself, but feel free to take a look at it. I've marked important changes with * characters, and changes that might be important with ? characters. Changes with no special character at the front _might_ be unnecessary in System3-SDL.

https://pastebin.com/6LzxqpGr

If you want any help with this merge, I'd be happy to help, but I know this has been a solo project for you and I wouldn't want to get in the way.  You certainly understand the program best, since I've barely started with it! Good luck either way, this is a big surprise I'm sure neither of us were expecting.

**Comment by kichikuou** [comment]
Thanks! Your notes are _super_ helpful.

I've started merging the changes. You can watch my progress [here](https://github.com/kichikuou/system3-sdl2/pull/3). Hopefully most of them can be mechanically translated so it won't take too long.

I wasn't expecting this indeed. I kinda regret that I made some big changes on my fork that made merge harder, but I'm glad I didn't completely rewrite the code (for example using clang-format) that would make automatic merging impossible.

**Comment by RottenBlock** [comment]
I'll keep an eye on your progress, for sure!

I know what you mean about making big changes. I wasn't going to go so far as to change to clang, but I was going to work on System 2 support at some point. Do you think there's any sense in reaching out to him?

**Comment by kichikuou** [comment]
The merge is complete.

Yeah now that we know the TOTO's project is "alive", it's a good idea to reach out to him and let him know what you're going to work on. Would you like me to send first email to him?

**Comment by RottenBlock** [comment]
Great job! Very quickly done!

Yes, that would be best. I'm afraid I don't speak the language.

**Comment by kichikuou** [comment]
Sent an email. I'll get back to you when I get a reply from him.

**Comment by kichikuou** [comment]
@RottenBlock I've received a response from TOTO.

I was telling him about your works and asking him about his future plans for the project. His reply was:

- He does not plan to make any major structural changes.
- He will fix some commands (especially Y command) as well as display location of text / messages in some softs.

He also said he may accept patches, but since he made this as a generic game engine, he's reluctant to add game-specific commands like those used in RPGs.


Given that, I think we shouldn't worry too much about conflicting or duplicated work. Also probably we shouldn't try too hard to upstream our changes, except for simple bug fixes.

**Comment by RottenBlock** [comment]
Thanks again for the emails. I agree, we can probably do our work without any worry at this point.

At this stage, I'm going to go ahead with moving my English language support from TOTO's version and over to yours. I may not be able to give it a priority for a few days, but I'll keep you informed!

**Comment by kichikuou** [comment]
Good luck with porting the English support!

Take your time - for the time being, I don't plan to make any code changes that will conflict with your work.
