### ISSUE TITLE
Intruder -桜屋敷の探索-

### ISSUE THREAD

**Issue by alan-zxs** [kichikuou/system3-sdl2#31]
1. I unpacked a game image file for the PC98/FM TOWNS version and placed system3-sdl2 v1.2.0 in it. The game launched, but the images do not display. I can only see text on a black background. It seems that system3-sdl2 could not read the [ACG.DAT](https://github.com/user-attachments/files/18044502/original.ACG.DAT.zip) file. 
I found an unofficial [Windows version ](http://retropc.net/alice/05.html)(based on the FM TOWNS) with a [modified ACG.DAT](https://github.com/user-attachments/files/18044529/modified.ACG.DAT.zip) file. For some reason, this file is larger than the original. When I use this modified file, the images are displayed in the game.
2. When I go down to the basement of the house and turn on the lamp, the screen doesn't change and remains black. I [recorded a video](https://www.youtube.com/watch?v=FWNZTdXZmSc): the PC98 version is on the left, and the Windows version is on the right. 
(The Scenario Decoder was used here, but the same issue occurs with system3-sdl2 v1.2.0)
I’m not sure if this is related to the modified ACG.DAT file or if some script was not implemented in system3-sdl.
This is a minor issue; the game logic continues to function despite the absence of image.

**Comment by kichikuou** [comment]
1. The PC-98 version of the game was a user port from the FM TOWNS version, and the Windows version is based on the PC-98 version ([reference](https://alicecottage1989.blog.jp/archives/15825078.html)). When the game was ported to Windows, its image format was converted to the one used by other AliceSoft games. Since system3-sdl2 is derived from this Windows version's game engine, it can run the Windows version. Making system3-sdl2 compatible with the PC-98 or FM TOWNS versions is currently outside the scope of this project.
2. This does appear to be a bug. I will investigate further.

**Comment by kichikuou** [comment]
> 2. This does appear to be a bug. I will investigate further.

This is fixed in version 1.2.1.
